Repository PA-Plasma/annual-project, pull requests merged in 2019-02, with the labels that each got.

#35 MERGE: fix:login into dev
  public/src/Security/LoginFormAuthenticator.php
Labels: bug, pending review

#34 MERGE: fix/eventBack into dev
  public/src/Controller/Back/EventController.php
  public/src/Form/EventType.php
Labels: bug, pending review

#39 MERGE : Feat/modules into dev
  public/src/Controller/Back/EventController.php
  public/src/Controller/Front/DefaultController.php
  public/src/Controller/Front/EventController.php
  public/src/Controller/Interfaces/ModuleInterface.php
  public/src/Entity/Modules.php
  public/src/Form/ModulesType.php
  public/src/Service/Modules/BetModuleHelper.php
  public/src/Service/Modules/ModulesInterface.php
  public/src/Service/ModulesHelper.php
Labels: code, pending review

#42 MERGE: feat/command into dev
  public/src/Command/CreateUserCommand.php
  public/src/Command/PromoteUserCommand.php
Labels: pending review

#44 MERGE: Feat/izitoast into dev
  public/assets/css/app.scss
  public/assets/js/app.js
  public/package.json
  public/src/Controller/Front/SecurityController.php
  public/src/Security/LoginFormAuthenticator.php
  public/templates/front/security/login.html.twig
  public/templates/page/messages.html.twig
Labels: code, pending review

#53 MERGE: Feat/auto login into dev
  public/src/Controller/Front/SecurityController.php
Labels: code, pending review

#51 MERGE: Feat/module tournoi into dev
  public/assets/js/moduleTournament.js
  public/src/Controller/Front/EventController.php
  public/src/Controller/Interfaces/ModuleInterface.php
  public/src/Controller/Modules/TournamentModuleController.php
  public/src/Entity/Event.php
  public/src/Entity/Interfaces/ModuleInterface.php
  public/src/Entity/Modules/ModuleTournament.php
  public/src/Entity/Modules/ModuleTournamentParameters.php
  public/src/Form/ModuleTournamentParametersType.php
  public/src/Repository/Modules/ModuleTournamentParametersRepository.php
  public/src/Repository/Modules/ModuleTournamentRepository.php
  public/src/Service/ModulesHelper.php
  public/templates/Modules/ModuleTournament/_form.html.twig
  public/templates/Modules/ModuleTournament/edit.html.twig
  public/templates/Modules/ModuleTournament/index.html.twig
  public/templates/Modules/ModuleTournament/new.html.twig
  public/templates/Modules/ModuleTournament/show.html.twig
  public/templates/Modules/base.html.twig
  public/templates/front/event/index.html.twig
  public/templates/front/event/show.html.twig
  public/webpack.config.js
Labels: pending review

#54 MERGE Fix/module tournament into dev
  public/assets/js/moduleTournament.js
  public/package-lock.json
  public/src/Controller/Modules/TournamentModuleController.php
  public/src/Service/ModulesHelper.php
  public/templates/Modules/ModuleTournament/new.html.twig
  public/templates/Modules/base.html.twig
Labels: review validated

#56 PR: feat/voters into dev
  public/config/packages/security.yaml
  public/src/Controller/Front/EventController.php
  public/src/Security/EventVoter.php
Labels: pending review

#52 MERGE: Feat/public event register into dev
  public/assets/js/app.js
  public/src/Controller/Front/EventController.php
  public/src/Repository/EventRepository.php
  public/templates/front/event/show.html.twig
  public/templates/page/modalCancelRegisterEvent.html.twig
  public/templates/page/modalRegisterEvent.html.twig
Labels: code, pending review

#58 MERGE: Fix/entrant into dev
  public/assets/css/app.scss
  public/assets/js/formEvent.js
  public/package-lock.json
  public/src/Controller/Ajax/UserController.php
  public/src/Controller/Front/EventController.php
  public/src/Entity/Entrant.php
  public/src/Form/EntrantType.php
  public/src/Migrations/Version20190223184313.php
  public/src/Migrations/Version20190224164719.php
  public/src/Repository/UserRepository.php
  public/templates/front/event/_form.html.twig
Labels: code, pending review

#60 fix/playerRegister : auto set email for public event registration
  public/src/Controller/Front/EventController.php
Labels: bug, pending review
