Repository PA-Plasma/annual-project, pull requests merged in 2019-01, with the labels that each got.

#4 MERGE: feat/github into dev
  .github/pull_request_template.md
Labels: review validated

#8 MERGE: feat/basic_controllers into dev
  public/config/packages/security.yaml
  public/src/Controller/Back/DefaultController.php
  public/src/Controller/Back/UserController.php
  public/src/Controller/Front/DefaultController.php
  public/src/Entity/User.php
  public/src/Form/UserType.php
  public/src/Repository/UserRepository.php
  public/src/Service/RolesHelper.php
  public/templates/back/default/index.html.twig
  public/templates/back/user/_delete_form.html.twig
  public/templates/back/user/_form.html.twig
  public/templates/back/user/edit.html.twig
  public/templates/back/user/index.html.twig
  public/templates/back/user/new.html.twig
  public/templates/back/user/show.html.twig
  public/templates/front/default/index.html.twig
Labels: review validated

#7 MERGE : fix/docker_bdd into dev
  docker-compose.yml
  public/.env
  public/config/packages/doctrine.yaml
Labels: review validated

#17 MERGE: feat/event-database into dev
  .gitignore
  public/.gitignore
  public/composer.lock
  public/src/Controller/Back/AddressController.php
  public/src/Controller/Back/EntrantController.php
  public/src/Controller/Back/EventController.php
  public/src/Entity/Address.php
  public/src/Entity/Entrant.php
  public/src/Entity/Event.php
  public/src/Entity/User.php
  public/src/Form/AddressType.php
  public/src/Form/EntrantType.php
  public/src/Form/EventType.php
  public/src/Repository/AddressRepository.php
  public/src/Repository/EntrantRepository.php
  public/src/Repository/EventRepository.php
  public/templates/address/_delete_form.html.twig
  public/templates/address/_form.html.twig
  public/templates/address/edit.html.twig
  public/templates/address/index.html.twig
  public/templates/address/new.html.twig
  public/templates/address/show.html.twig
  public/templates/entrant/_delete_form.html.twig
  public/templates/entrant/_form.html.twig
  public/templates/entrant/edit.html.twig
  public/templates/entrant/index.html.twig
  public/templates/entrant/new.html.twig
  public/templates/entrant/show.html.twig
  public/templates/event/_delete_form.html.twig
  public/templates/event/_form.html.twig
  public/templates/event/edit.html.twig
  public/templates/event/index.html.twig
  public/templates/event/new.html.twig
  public/templates/event/show.html.twig
Labels: code, pending review

#19 MERGE: feat/bootstrap into dev
  public/assets/css/app.scss
  public/package.json
  public/webpack.config.js
  public/yarn.lock
Labels: code, pending review

#20 MERGE: feat/auth into dev
  public/composer.json
  public/composer.lock
  public/config/bundles.php
  public/config/packages/security.yaml
  public/config/packages/stof_doctrine_extensions.yaml
  public/config/routes.yaml
  public/src/Controller/Back/UserController.php
  public/src/Controller/Front/SecurityController.php
  public/src/Entity/Traits/ActiveTrait.php
  public/src/Entity/Traits/SoftDeletedTrait.php
  public/src/Entity/Traits/TimestampableTrait.php
  public/src/Entity/Traits/TimestampableUserTrait.php
  public/src/Entity/User.php
  public/src/Form/UserType.php
  public/symfony.lock
  public/templates/back/user/_delete_form.html.twig
  public/templates/back/user/index.html.twig
  public/templates/back/user/show.html.twig
  public/templates/base.html.twig
  public/templates/front/default/header.html.twig
  public/templates/front/security/login.html.twig
  public/templates/front/security/register.html.twig
Labels: review validated

#24 MERGE: feat/auth into dev
  public/composer.lock
  public/config/packages/security.yaml
  public/src/Security/LoginFormAuthenticator.php
  public/templates/front/security/login.html.twig
Labels: pending review

#25 MERGE: feat/autocomplete-entrant into dev
  public/assets/js/app.js
  public/assets/js/formEvent.js
  public/package-lock.json
  public/package.json
  public/src/Controller/Ajax/UserController.php
  public/src/Controller/Back/EventController.php
  public/src/Entity/Entrant.php
  public/src/Entity/Event.php
  public/src/Form/EntrantType.php
  public/src/Form/EventType.php
  public/src/Repository/UserRepository.php
  public/templates/back/event/_delete_form.html.twig
  public/templates/back/event/_form.html.twig
  public/templates/back/event/edit.html.twig
  public/templates/back/event/index.html.twig
  public/templates/back/event/new.html.twig
  public/templates/back/event/show.html.twig
  public/templates/event/_form.html.twig
  public/templates/front/event/_delete_form.html.twig
  public/templates/front/event/_form.html.twig
  public/templates/front/event/edit.html.twig
  public/templates/front/event/index.html.twig
  public/templates/front/event/new.html.twig
  public/templates/front/event/show.html.twig
  public/webpack.config.js
Labels: pending review

#27 MERGE: fix/controller_name into dev
  public/src/Controller/Back/AddressController.php
  public/src/Controller/Back/EntrantController.php
  public/src/Controller/Back/EventController.php
  public/src/Controller/Back/UserController.php
  public/templates/back/address/_delete_form.html.twig
  public/templates/back/address/_form.html.twig
  public/templates/back/address/index.html.twig
  public/templates/back/address/new.html.twig
  public/templates/back/address/show.html.twig
  public/templates/back/entrant/_delete_form.html.twig
  public/templates/back/entrant/_form.html.twig
  public/templates/back/entrant/edit.html.twig
  public/templates/back/entrant/index.html.twig
  public/templates/back/entrant/new.html.twig
  public/templates/back/entrant/show.html.twig
  public/templates/entrant/edit.html.twig
Labels: pending review

#28 MERGE: autocomplete-entrant into dev
  public/src/Controller/Front/EventController.php
Labels: pending review

#30 Feat/event crud
  public/src/Controller/Front/EventController.php
  public/templates/back/address/edit.html.twig
  public/templates/back/event/_delete_form.html.twig
  public/templates/back/event/edit.html.twig
  public/templates/back/event/index.html.twig
  public/templates/back/event/new.html.twig
  public/templates/back/event/show.html.twig
  public/templates/front/event/_delete_form.html.twig
  public/templates/front/event/edit.html.twig
  public/templates/front/event/show.html.twig
Labels: pending review

#32 MERGE: feat/basic_front into dev
  public/assets/css/app.scss
  public/assets/js/app.js
  public/package-lock.json
  public/package.json
  public/src/Controller/Front/DefaultController.php
  public/src/Controller/Front/SecurityController.php
  public/src/Form/AddressType.php
  public/src/Form/EntrantType.php
  public/src/Form/EventType.php
  public/src/Form/UserType.php
  public/templates/address/edit.html.twig
  public/templates/back/address/_delete_form.html.twig
  public/templates/back/address/_form.html.twig
  public/templates/back/address/edit.html.twig
  public/templates/back/address/index.html.twig
  public/templates/back/address/new.html.twig
  public/templates/back/address/show.html.twig
  public/templates/back/entrant/_delete_form.html.twig
  public/templates/back/entrant/_form.html.twig
  public/templates/back/entrant/edit.html.twig
  public/templates/back/entrant/index.html.twig
  public/templates/back/entrant/new.html.twig
  public/templates/back/entrant/show.html.twig
  public/templates/back/event/_delete_form.html.twig
  public/templates/back/event/_form.html.twig
  public/templates/back/event/edit.html.twig
  public/templates/back/event/index.html.twig
  public/templates/back/event/new.html.twig
  public/templates/back/event/show.html.twig
  public/templates/back/user/_delete_form.html.twig
  public/templates/back/user/_form.html.twig
  public/templates/back/user/edit.html.twig
  public/templates/back/user/index.html.twig
  public/templates/back/user/new.html.twig
  public/templates/back/user/show.html.twig
  public/templates/base.html.twig
  public/templates/front/default/header.html.twig
  public/templates/front/event/_delete_form.html.twig
  public/templates/front/event/_form.html.twig
  public/templates/front/event/edit.html.twig
  public/templates/front/event/index.html.twig
  public/templates/front/event/new.html.twig
  public/templates/front/event/show.html.twig
  public/templates/front/security/login.html.twig
  public/templates/front/security/register.html.twig
  public/templates/page/header.html.twig
  public/templates/page/messages.html.twig
  public/templates/page/operations.html.twig
  public/templates/page/return.html.twig
  public/yarn.lock
Labels: pending review

#33 MERGE: feat/traits_and_slug into dev
  public/src/Controller/Back/AddressController.php
  public/src/Controller/Back/EntrantController.php
  public/src/Controller/Back/EventController.php
  public/src/Controller/Back/UserController.php
  public/src/Controller/Front/EventController.php
  public/src/Entity/Address.php
  public/src/Entity/Entrant.php
  public/src/Entity/Event.php
  public/src/Entity/User.php
  public/templates/page/operations.html.twig
Labels: pending review
